// Comics Data
const comics = [
  {
    id: "CBH001",
    title: "Watchmen",
    publisher: "DC",
    character: "Rorschach, Dr. Manhattan, Ozymandias, Silk Spectre",
    genre: "Superhero",
    price: 831, 
    releaseDate: "1986-09-01",
    coverImage: "https://m.media-amazon.com/images/I/61BvMZbTw9L._AC_UF1000,1000_QL80_.jpg",
    description: "A deconstruction of the superhero genre, exploring power, morality, and identity.",
    creators: { writer: "Alan Moore", artist: "Dave Gibbons", colorist: "John Higgins" },
    pages: 416,
    featured: true,
    popular: true
  },
  {
    id: "CBH002",
    title: "The Sandman",
    publisher: "DC / Vertigo",
    character: "Dream, Death, Lucifer",
    genre: "Fantasy",
    price: 1079, 
    releaseDate: "1989-01-01",
    coverImage: "https://m.media-amazon.com/images/I/91KatT7rE8L._AC_UF1000,1000_QL80_.jpg",
    description: "Dream, the Lord of Dreams, navigates the realms of the waking and sleeping worlds.",
    creators: { writer: "Neil Gaiman", artist: "various", colorist: "Dave McKean" },
    pages: 240,
    featured: true,
    popular: true
  },
  {
    id: "CBH003",
    title: "Bone",
    publisher: "Cartoon Books",
    character: "Fone Bone, Phoney Bone, Smiley Bone",
    genre: "Fantasy",
    price: 663, 
    releaseDate: "1991-07-01",
    coverImage: "https://m.media-amazon.com/images/I/819vThpT3iL._AC_UF1000,1000_QL80_.jpg",
    description: "Three Bone cousins are run out of their home and go on a surreal fantasy adventure.",
    creators: { writer: "Jeff Smith", artist: "Jeff Smith", colorist: "Jeff Smith" },
    pages: 1336,
    featured: false,
    popular: false
  },
  {
    id: "CBH004",
    title: "Maus",
    publisher: "Pantheon / Raw",
    character: "Vladek Spiegelman, Art Spiegelman",
    genre: "Historical / Biography",
    price: 1245, 
    releaseDate: "1991-11-01",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/7/7d/Maus_%28volume_1%29_cover.jpg",
    description: "A Holocaust survivor’s story told through anthropomorphic mice and cats.",
    creators: { writer: "Art Spiegelman", artist: "Art Spiegelman", colorist: "Art Spiegelman" },
    pages: 296,
    featured: true,
    popular: false
  },
  {
    id: "CBH005",
    title: "Batman: The Dark Knight Returns",
    publisher: "DC",
    character: "Batman, Joker, Superman",
    genre: "Superhero",
    price: 995, 
    releaseDate: "1986-02-01",
    coverImage: "https://m.media-amazon.com/images/I/71JGiMGuZuL._UF350,350_QL50_.jpg",
    description: "An aged Bruce Wayne returns as Batman in a dystopian, crime-ridden future.",
    creators: { writer: "Frank Miller", artist: "Frank Miller", colorist: "Klaus Janson" },
    pages: 224,
    featured: false,
    popular: true
  },
  {
    id: "CBH006",
    title: "Hawkeye",
    publisher: "Marvel",
    character: "Clint Barton, Kate Bishop",
    genre: "Superhero",
    price: 746, 
    releaseDate: "2012-11-07",
    coverImage: "https://m.media-amazon.com/images/I/91-Xo+JO52L._UF1000,1000_QL80_.jpg",
    description: "The story of Clint Barton — a quieter, more personal take on a superhero’s life.",
    creators: { writer: "Matt Fraction", artist: "David Aja", colorist: "Matt Hollingsworth" },
    pages: 128,
    featured: false,
    popular: false
  },
  {
    id: "CBH007",
    title: "V for Vendetta",
    publisher: "DC / Vertigo",
    character: "V, Evey Hammond",
    genre: "Political Thriller",
    price: 912, 
    releaseDate: "1988-03-01",
    coverImage: "https://upload.wikimedia.org/wikipedia/en/c/c0/V_for_vendettax.jpg",
    description: "A masked vigilante fights a totalitarian regime in a dystopian Britain.",
    creators: { writer: "Alan Moore", artist: "David Lloyd", colorist: "David Lloyd" },
    pages: 296,
    featured: true,
    popular: true
  },
  {
    id: "CBH008",
    title: "Y: The Last Man",
    publisher: "DC / Vertigo",
    character: "Yorick Brown, Ampersand",
    genre: "Post-Apocalyptic",
    price: 995, 
    releaseDate: "2002-09-01",
    coverImage: "https://m.media-amazon.com/images/I/71lBTGxPOOL._AC_UF1000,1000_QL80_.jpg",
    description: "The story of the last surviving man on Earth after a mysterious plague wipes out males.",
    creators: { writer: "Brian K. Vaughan", artist: "Pia Guerra", colorist: "Betsy Gonia" },
    pages: 380,
    featured: true,
    popular: true
  },
  {
    id: "CBH009",
    title: "Persepolis",
    publisher: "L'Association / Pantheon",
    character: "Marjane Satrapi",
    genre: "Autobiography / Historical",
    price: 831, 
    releaseDate: "2000-10-01",
    coverImage: "https://m.media-amazon.com/images/I/616z6dC0bYL._AC_UF1000,1000_QL80_.jpg",
    description: "A young girl grows up during the Iranian Revolution in this autobiographical graphic novel.",
    creators: { writer: "Marjane Satrapi", artist: "Marjane Satrapi", colorist: "Marjane Satrapi" },
    pages: 153,
    featured: true,
    popular: false
  },
  {
    id: "CBH010",
    title: "Saga",
    publisher: "Image",
    character: "Alana, Marko, Hazel",
    genre: "Space Opera / Fantasy",
    price: 1079, 
    releaseDate: "2012-03-01",
    coverImage: "https://m.media-amazon.com/images/I/615T6Z-clpL._AC_UF1000,1000_QL80_.jpg",
    description: "An epic tale of a family caught in an intergalactic war.",
    creators: { writer: "Brian K. Vaughan", artist: "Fiona Staples", colorist: "Fiona Staples" },
    pages: 192,
    featured: true,
    popular: true
  },
  {
    id: "CBH011",
    title: "Ms. Marvel (Kamala Khan)",
    publisher: "Marvel",
    character: "Kamala Khan, Aamir Khan",
    genre: "Superhero",
    price: 663, 
    releaseDate: "2014-02-01",
    coverImage: "https://m.media-amazon.com/images/I/81YON76gaQL._UF1000,1000_QL80_.jpg",
    description: "A Pakistani-American teenager discovers her superpowers and identity as Ms. Marvel.",
    creators: { writer: "G. Willow Wilson", artist: "Adrian Alphona", colorist: "Ian Herring" },
    pages: 120,
    featured: false,
    popular: true
  },
  {
    id: "CBH012",
    title: "Black Panther",
    publisher: "Marvel",
    character: "T'Challa, Shuri, Killmonger",
    genre: "Superhero",
    price: 746, 
    releaseDate: "1977-01-01",
    coverImage: "https://m.media-amazon.com/images/I/81Dh5cA7LuL._AC_UF1000,1000_QL80_.jpg",
    description: "The adventures of T'Challa, the king of Wakanda, balancing duty and heroism.",
    creators: { writer: "Jack Kirby", artist: "John Romita Sr.", colorist: "Tom Palmer" },
    pages: 250,
    featured: true,
    popular: true
  },
  {
    id: "CBH013",
    title: "Infinity Gauntlet",
    publisher: "Marvel",
    character: "Thanos, Iron Man, Spider-Man, Captain America",
    genre: "Superhero",
    price: 1079, 
    releaseDate: "1991-07-01",
    coverImage: "https://m.media-amazon.com/images/I/91HemAcOl9L.jpg",
    description: "Thanos acquires the Infinity Gauntlet and threatens the universe with ultimate power.",
    creators: { writer: "Jim Starlin", artist: "George Perez", colorist: "Joe Rosas" },
    pages: 200,
    featured: true,
    popular: true
  },
  {
    id: "CBH014",
    title: "Spider-Man: Blue",
    publisher: "Marvel",
    character: "Peter Parker, Gwen Stacy",
    genre: "Superhero / Romance",
    price: 831, 
    releaseDate: "2002-06-01",
    coverImage: "https://m.media-amazon.com/images/I/81YOKRqxRnL._UF1000,1000_QL80_.jpg",
    description: "Peter Parker reflects on his early days and the love he lost.",
    creators: { writer: "Jeph Loeb", artist: "Tim Sale", colorist: "Matthew Wilson" },
    pages: 110,
    featured: false,
    popular: true
  },
  {
    id: "CBH015",
    title: "Civil War",
    publisher: "Marvel",
    character: "Iron Man, Captain America, Spider-Man",
    genre: "Superhero",
    price: 1245, 
    releaseDate: "2006-05-01",
    coverImage: "https://m.media-amazon.com/images/I/91JWshL0WSL._AC_UF1000,1000_QL80_.jpg",
    description: "A government mandate splits the superhero community, pitting hero against hero.",
    creators: { writer: "Mark Millar", artist: "Steve McNiven", colorist: "Morry Hollowell" },
    pages: 384,
    featured: true,
    popular: true
  },
  {
    id: "CBH016",
    title: "All-Star Superman",
    publisher: "DC",
    character: "Superman, Lois Lane, Lex Luthor",
    genre: "Superhero",
    price: 1159, 
    releaseDate: "2006-11-01",
    coverImage: "https://m.media-amazon.com/images/I/81UsnOXb5zL.jpg",
    description: "Superman faces his mortality while leaving a legacy of hope and heroism.",
    creators: { writer: "Grant Morrison", artist: "Frank Quitely", colorist: "Alex Sinclair" },
    pages: 320,
    featured: true,
    popular: true
  },
  {
    id: "CBH017",
    title: "Kingdom Come",
    publisher: "DC",
    character: "Superman, Batman, Wonder Woman",
    genre: "Superhero / Dystopia",
    price: 1079, 
    releaseDate: "1996-05-01",
    coverImage: "https://m.media-amazon.com/images/I/71X2fMI3p1L._AC_UF1000,1000_QL80_.jpg",
    description: "A future where traditional heroes return to challenge a new, reckless generation.",
    creators: { writer: "Mark Waid", artist: "Alex Ross", colorist: "Alex Ross" },
    pages: 208,
    featured: true,
    popular: true
  },
  {
    id: "CBH018",
    title: "Teenage Mutant Ninja Turtles: The Original Adventures",
    publisher: "Mirage Studios",
    character: "Leonardo, Michelangelo, Donatello, Raphael",
    genre: "Action / Comedy",
    price: 831,
    releaseDate: "1984-05-01",
    coverImage: "https://m.media-amazon.com/images/I/91RwLCyWLcL._AC_UF1000,1000_QL80_.jpg",
    description: "The four ninja turtles fight crime, facing villains and learning teamwork.",
    creators: { writer: "Kevin Eastman", artist: "Peter Laird", colorist: "Ryan Brown" },
    pages: 180,
    featured: false,
    popular: true
  },
  {
    id: "CBH019",
    title: "Watchmen: The Director's Cut",
    publisher: "DC",
    character: "Rorschach, Dr. Manhattan, Ozymandias, Silk Spectre",
    genre: "Superhero / Noir",
    price: 1327, 
    releaseDate: "2008-11-01",
    coverImage: "https://images.moviesanywhere.com/f353bd249c6b6ad2e46397034d60dec7/b34ee4f2-87aa-49d5-ac84-5a41d1431a21.jpg",
    description: "Expanded edition of Watchmen with extra content and behind-the-scenes notes.",
    creators: { writer: "Alan Moore", artist: "Dave Gibbons", colorist: "John Higgins" },
    pages: 440,
    featured: true,
    popular: true
  }
];
